In [11]:
import os
import tensorflow as tf
from PIL import Image
import numpy as np

full_video_dir = os.path.join('/Users/User/Desktop/MSc Project/English Cued Speech/FullVideo')
all_shapes_dir = os.path.join('/Users/User/Desktop/MSc Project/English Cued Speech/SelectedShapes')
consonants_dir = os.path.join('/Users/User/Desktop/MSc Project/English Cued Speech/SelectedShapes-Consonants')
vowels_dir = os.path.join('/Users/User/Desktop/MSc Project/English Cued Speech/SelectedShapes-Vowels')

In [181]:
with open("/Users/User/Desktop/MSc Project/English Cued Speech/Labels_Consonant.txt") as consonant_labels:

    consonant_lines = consonant_labels.readlines()
    #consonant_shape_labels = np.zeros(len(consonant_lines), dtype=str)
    #consonant_position_labels = np.zeros(len(consonant_lines), dtype=str)
    #consonant_phoneme_labels = np.zeros(len(consonant_lines), dtype=str)  
    #consonant_lines = np.asarray(consonant_lines)
    #consonant_line_split[:] = consonant_lines[:].split()
    #consonant_line = numpy.zeros
    #consonant_line = []
    consonant_shape_labels= [None] * len(consonant_lines)
    consonant_position_labels = [None] * len(consonant_lines)
    consonant_phoneme_labels = [None] * len(consonant_lines)
    for i, line in enumerate(consonant_lines):
        consonant_line = line.split()
   # for line in consonant_labels:
    #    consonant_line = line.split()
        #consonant_line = np.asarray(consonant_line)
        consonant_shape_labels[i]  = consonant_line[1]
        consonant_position_labels[i] = consonant_line[2]
        consonant_phoneme_labels[i] = consonant_line[3]
        print(consonant_line)
        print(consonant_phoneme_labels[i])
    #consonant_line = np.asarray(consonant_line)
    #consonant_shape_labels = consonant_line[:,1]
    #consonant_position_labels = consonant_line[:,2]
    #consonant_phoneme_labels = str(consonant_line[:,3])

print(consonant_shape_labels)
print(consonant_position_labels)
print(consonant_phoneme_labels)

['000059', '6', '3', '22']
22
['000064', '2', '3', '8']
8
['000074', '3', '1', '2']
2
['000080', '6', '4', '21']
21
['000084', '1', '4', '12']
12
['000089', '5', '4', '3']
3
['000098', '3', '1', '5']
5
['000113', '8', '2', '24']
24
['000128', '6', '4', '22']
22
['000142', '4', '4', '18']
18
['000168', '1', '2', '12']
12
['000309', '8', '2', '24']
24
['000320', '6', '4', '6']
6
['000336', '1', '4', '12']
12
['000344', '5', '1', '17']
17
['000356', '2', '2', '8']
8
['000366', '1', '1', '1']
1
['000379', '2', '4', '10']
10
['000387', '4', '4', '9']
9
['000396', '3', '2', '23']
23
['000405', '4', '4', '18']
18
['000411', '2', '4', '13']
13
['000423', '1', '1', '12']
12
['000441', '2', '4', '13']
13
['000585', '5', '2', '2']
2
['000593', '6', '4', '22']
22
['000598', '5', '4', '3']
3
['000607', '2', '4', '11']
11
['000618', '3', '2', '23']
23
['000630', '3', '4', '5']
5
['000637', '5', '3', '2']
2
['000646', '6', '4', '22']
22
['000653', '1', '3', '1']
1
['000659', '6', '4', '22']
22
['0006

['014673', '6', '1', "s'"]
s'
['014681', '6', '2', 'l']
l
['014690', '2', '4', 'k']
k
['014693', '5', '4', 't']
t
['014699', '2', '4', "t'"]
t'
['014709', '1', '1', 'd']
d
['014717', '2', '4', 'z']
z
['014730', '4', '4', 'n']
n
['014735', '1', '4', 'd']
d
['014750', '1', '4', 'p']
p
['014754', '5', '4', 't']
t
['014761', '3', '2', 'r']
r
['014778', '5', '4', 'f']
f
['014786', '3', '2', 'r']
r
['014792', '5', '4', 'm']
m
['014796', '3', '4', 'h']
h
['014804', '5', '2', 'f']
f
['014819', '3', '4', 's']
s
['015032', '2', '1', "t'"]
t'
['015048', '5', '4', 't']
t
['015056', '4', '2', 'n']
n
['015061', '5', '4', 't']
t
['015066', '1', '4', 'p']
p
['015073', '6', '2', 'l']
l
['015085', '2', '4', 'z']
z
['015098', '4', '4', 'n']
n
['015110', '1', '1', 'p']
p
['015116', '5', '4', 't']
t
['015120', '4', '4', 'n']
n
['015125', '3', '4', 'r']
r
['015140', '6', '4', 'l']
l
['015164', '6', '4', 'l']
l
['015180', '5', '4', 'f']
f
['015382', '3', '3', 'h']
h
['015388', '2', '4', 'z']
z
['015393', '4'

['024440', '5', '4', 'f']
f
['024448', '3', '3', 'r']
r
['024455', '4', '4', 'n']
n
['024461', '3', '3', 's']
s
['024468', '2', '4', 'k']
k
['024480', '3', '4', 'h']
h
['024498', '5', '4', 'm']
m
['024566', '8', '2', 'y']
y
['024575', '2', '4', 'v']
v
['024581', '1', '4', 'p']
p
['024589', '3', '2', 'r']
r
['024599', '4', '4', 'b']
b
['024607', '4', '4', 'b']
b
['024614', '6', '1', 'l']
l
['024620', '8', '2', 'y']
y
['024627', '2', '4', 'z']
z
['024633', '1', '4', 'd']
d
['024640', '8', '1', 'y']
y
['024652', '7', '3', 'g']
g
['024664', '5', '4', 'f']
f
['024689', '5', '3', 'f']
f
['024695', '7', '4', 'g']
g
['024702', '3', '4', 'r']
r
['024719', '6', '2', 'w']
w
['024732', '3', '4', 'r']
r
['024758', '5', '4', 'm']
m
['024906', '2', '4', 'v']
v
['024915', '4', '1', 'r']
r
['024922', '4', '2', 'b']
b
['024928', '1', '1', 'd']
d
['024935', '5', '2', 'f']
f
['024940', '6', '4', 'l']
l
['024951', '1', '4', 'd']
d
['024959', '3', '3', 'h']
h
['024965', '2', '4', 'z']
z
['024979', '7', '4',

In [69]:
print(len(consonant_shape_labels))
print(len(consonant_position_labels))
print(len(consonant_phoneme_labels))

1500
1500
1500


In [75]:
#print(consonant_shape_labels)
#print(consonant_position_labels)
print(consonant_phoneme_labels)
print(consonant_phoneme_labels[13])

['m' 'l' 'k' ... 't' 'n' 'd']
s


In [13]:
with open("/Users/User/Desktop/MSc Project/English Cued Speech/Labels-Vowels.txt") as vowel_labels:
    vowel_shape_labels = []
    vowel_position_labels = []
    vowel_phoneme_labels = []
    
    for line in vowel_labels:
        vowel_line_split = line.split()
        vowel_shape_labels += vowel_line_split[1]
        vowel_position_labels += vowel_line_split[2]
        vowel_phoneme_labels += vowel_line_split[3]
        print(vowel_line_split)

['000027', '5', '4', "a'"]
['000041', '5', '3', 'i']
['000049', '5', '3', 'a']
['000059', '6', '3', "u'"]
['000064', '2', '3', 'i']
['000074', '3', '1', "o'"]
['000080', '6', '4', "e'"]
['000089', '5', '4', "e'"]
['000098', '3', '1', "i'"]
['000103', '5', '3', 'i']
['000113', '8', '2', 'u~']
['000119', '5', '1', "o'"]
['000135', '5', '2', 'o']
['000161', '5', '3', 'i']
['000168', '1', '2', 'e']
['000177', '5', '3', 'i']
['000309', '8', '2', 'u~']
['000320', '6', '4', "e'"]
['000329', '5', '3', "u'"]
['000344', '5', '1', "i'"]
['000356', '2', '2', 'o']
['000366', '1', '1', "i'"]
['000374', '5', '2', 'o']
['000396', '3', '2', 'o']
['000423', '1', '1', "o'"]
['000576', '5', '3', 'i']
['000585', '5', '2', 'e']
['000607', '2', '4', "e'"]
['000618', '3', '2', 'e']
['000623', '5', '3', 'i']
['000637', '5', '3', "u'"]
['000653', '1', '3', 'i']
['000834', '5', '3', 'i']
['000860', '5', '2', 'e']
['000868', '5', '3', 'i']
['000874', '2', '3', 'i']
['000889', '3', '4', "a'"]
['000896', '5', '3', 

In [7]:
print(len(vowel_shape_labels))
print(len(vowel_position_labels))
print(len(vowel_phoneme_labels))

1146
1146
1754


In [10]:
#print(vowel_shape_labels)
#print(vowel_position_labels)
print(vowel_phoneme_labels)

['a', "'", 'i', 'a', 'u', "'", 'i', 'o', "'", 'e', "'", 'e', "'", 'i', "'", 'i', 'u', '~', 'o', "'", 'o', 'i', 'e', 'i', 'u', '~', 'e', "'", 'u', "'", 'i', "'", 'o', 'i', "'", 'o', 'o', 'o', "'", 'i', 'e', 'e', "'", 'e', 'i', 'u', "'", 'i', 'i', 'e', 'i', 'i', 'a', "'", 'u', "'", 'e', "'", 'a', 'o', "'", 'e', "'", 'a', "'", 'i', 'i', 'i', 'e', 'i', 'i', 'e', "'", 'e', 'i', 'i', 'a', "'", 'u', "'", 'a', 'e', "'", 'i', "'", 'e', "'", 'a', 'o', "'", 'e', "'", 'a', "'", 'i', 'i', 'i', 'e', 'i', 'i', 'e', 'i', 'i', 'a', "'", 'u', "'", 'a', 'e', "'", 'i', "'", 'e', "'", 'a', 'o', "'", 'e', "'", 'a', "'", 'i', 'i', 'i', 'e', 'e', 'i', 'e', "'", 'a', "'", 'i', 'e', 'e', "'", 'u', "'", 'e', "'", 'e', 'i', 'e', 'i', 'o', 'e', "'", 'a', "'", 'i', 'o', "'", 'a', "'", 'i', 'a', "'", 'i', 'a', "'", 'i', 'u', "'", 'i', "'", 'e', 'i', "'", 'i', 'e', 'i', 'i', 'i', "'", 'a', 'i', "'", 'o', 'e', "'", 'u', "'", 'a', "'", 'i', 'i', "'", 'e', "'", 'e', 'i', 'o', 'a', 'i', 'e', "'", 'i', 'i', 'e', "'", 'e',

In [1]:
with open("/Users/User/Desktop/MSc Project/English Cued Speech/Phonemes_Vowel.txt") as vowel_labels:
    vowel_lines = vowel_labels.readlines()

    vowel_shape_labels = [None] * len(vowel_lines)
    vowel_position_labels = [None] * len(vowel_lines)
    vowel_phoneme_labels = [None] * len(vowel_lines)
    for i, line in enumerate(vowel_lines):
        vowel_line = line.split()
   # for line in consonant_labels:
    #    consonant_line = line.split()
        #consonant_line = np.asarray(consonant_line)
        vowel_shape_labels[i]  = vowel_line[1]
        vowel_position_labels[i] = vowel_line[2]
        vowel_phoneme_labels[i] = vowel_line[3]
        #print(vowel_line)
        #print(vowel_phoneme_labels[i])
    #consonant_line = np.asarray(consonant_line)
    #consonant_shape_labels = consonant_line[:,1]
    #consonant_position_labels = consonant_line[:,2]
    #consonant_phoneme_labels = str(consonant_line[:,3])
#print(len(vowel_lines))
#print(len(vowel_shape_labels))
#print(len(vowel_position_labels))
#print(len(vowel_phoneme_labels))
#print(vowel_shape_labels)
#print(vowel_position_labels)
#print(vowel_phoneme_labels)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/User/Desktop/MSc Project/English Cued Speech/Phonemes_Vowel.txt'

In [28]:
    with open("/Users/User/Desktop/MSc Project/English Cued Speech/Labels_All.txt") as file_labels:

        file_lines = file_labels.readlines()

        file_shape_labels= [None] * len(file_lines)
        file_position_labels = [None] * len(file_lines)
        file_phoneme_labels = [None] * len(file_lines)
        file_second_phoneme_labels = [None] * len(file_lines)
        
        for i, line in enumerate(file_lines):
            file_line = line.split()

            file_shape_labels[i]  = file_line[1]
            file_position_labels[i] = file_line[2]
            file_phoneme_labels[i] = file_line[3]
            file_second_phoneme_labels[i] = file_line[4]
            #print(file_line[4])

            #print(file_line)
            #print(file_second_phoneme_label)            
        print(len(file_lines))
        print(len(file_shape_labels))
        print(len(file_position_labels))
        print(len(file_phoneme_labels))
        print(len(file_second_phoneme_labels))

1816
1816
1816
1816
1816


In [21]:
#Function to extract labels from files
def extract_labels(file_path):
    with open(file_path) as file_labels:

        file_lines = file_labels.readlines()

        file_shape_labels= [None] * len(file_lines)
        file_position_labels = [None] * len(file_lines)
        file_phoneme_labels = [None] * len(file_lines)
        file_second_phoneme_label = [None] * len(file_lines)  #<-- Uncomment this line when using for combined labels
        
        for i, line in enumerate(file_lines):
            file_line = line.split()

            file_shape_labels[i]  = int(file_line[1])
            file_position_labels[i] = int(file_line[2])
            file_phoneme_labels[i] = int(file_line[3])
            file_second_phoneme_label[i] = int(file_line[4])  #<-- Uncomment this line when using for combined labels
            
    return (np.array(file_shape_labels), np.array(file_position_labels), np.array(file_phoneme_labels), np.array(file_second_phoneme_label)) #<-- Uncomment this when using for combined labels


In [32]:
test_labels = "/Users/User/Desktop/MSc Project/English Cued Speech/Labels_Consonant_test.txt"
(test_shape_labels, test_position_labels, test_phoneme_labels, not_used) = extract_labels(test_labels)

In [2]:
xx = np.arange(10)

np.random.shuffle(xx)
print(xx)

[5 6 4 1 9 3 0 7 8 2]


In [28]:
xx = np.random.choice(np.arange(10), replace = False, size = 10)
xx

array([6, 4, 7, 9, 2, 8, 0, 1, 5, 3])

In [23]:
#Extract labels
(consonant_shape_labels, consonant_position_labels, consonant_phoneme_labels, not_used) = extract_labels(consonant_labels)
(vowel_shape_labels, vowel_position_labels, vowel_phoneme_labels, or_this) = extract_labels(vowel_labels)
(combined_shape_labels, combined_position_labels, combined_consonant_labels, combined_vowel_labels) = extract_labels(combined_labels)

In [5]:
#Open image folders
consonants_dir = os.path.join('/Users/User/Desktop/MSc Project/English Cued Speech/SelectedShapes-Consonants/')
vowels_dir = os.path.join('/Users/User/Desktop/MSc Project/English Cued Speech/SelectedShapes-Vowels/')
combined_dir = os.path.join('/Users/User/Desktop/MSc Project/English Cued Speech/SmallerImages/')

#Open label files
consonant_labels = "/Users/User/Desktop/MSc Project/English Cued Speech/Labels_Consonant.txt"
vowel_labels = "/Users/User/Desktop/MSc Project/English Cued Speech/Labels_Vowel.txt"
combined_labels = "/Users/User/Desktop/MSc Project/English Cued Speech/Labels_All.txt"

In [7]:
#Funtion to randomly shuffle data
def shuffle_data(images, labels):
    #index = np.arange(len(labels))
    #np.shuffle(index)
    index = np.random.choice(np.arange(len(labels)), replace = False, size = len(labels))
    
    shuffled_images = images[index]
    shuffled_labels = labels[index]
    return shuffled_images, shuffled_labels

In [8]:
#Function to split data
def split_data(data, split_ratio=0.9):
    partition = round(len(data) * split_ratio)
    
    train = data[:partition]
    test = data[partition:]
    return train, test

In [9]:
def create_dataset(image_dir):
    dataset = []
    for image_name in os.listdir(image_dir):
        image = Image.open(image_dir + image_name)
        image_as_array = np.asarray(image)
        #norm_image = image_as_array / 255
        dataset.append(image_as_array)
    return np.array(dataset)

In [12]:
test_set = create_dataset(combined_dir)

In [13]:
print((test_set))

[[[[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]]

  [[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]]

  [[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]]

  ...

  [[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]]

  [[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]]

  [[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]]]


 [[[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]]

  [[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]]

  [[ 13  32 244]
   [ 13  32 244]
   [ 13  32 244]
   ...
   [ 13  32 244]
   [ 13  32 244]
   [ 13  32

In [14]:
#test_set2 = test_set.reshape(len(test_set), 256, 256, 3)
test_set2 = test_set /255.0
print(test_set2)

[[[[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  ...

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.0

In [15]:
train, test = split_data(test_set2)

In [16]:
print(len(test_set2))
print(len(train))
print(len(test))

1816
1634
182


In [17]:
print(train)

[[[[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  ...

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.0

In [18]:
print(test)

[[[[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  ...

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05490196 0.1254902  0.96078431]
   [0.05882353 0.1254902  0.96078431]]

  [[0.05098039 0.1254902  0.95686275]
   [0.0

In [24]:
shuffled_images, shuffled_labels = shuffle_data(test_set2, combined_consonant_labels)

In [25]:
print(len(shuffled_images))
print(len(shuffled_labels))

1816
1816


In [26]:
print((shuffled_images))
print((shuffled_labels))

[[[[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]]

  ...

  [[0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   [0.05098039 0.1254902  0.95686275]
   ...
   [0.05490196 0.1254902  0.96078431]
   [0.0745098  0.12941176 0.94901961]
   [0.08235294 0.1254902  0.94117647]]

  [[0.05098039 0.1254902  0.95686275]
   [0.0

In [ ]:
vowel_images = create_dataset(vowels_dir)
vowel_images = vowel_images.reshape(len(vowel_images), 256, 256, 3)
#vowel_images = vowel_images / 255

In [ ]:
shuffled_vowels, shuffled_vowel_position_labels = shuffle_data(vowel_images, vowel_position_labels)

In [ ]:
vowel_train, vowel_test = split_data(shuffled_vowels)
vowel_position_labels_train, vowel_position_labels_test = split_data(shuffled_vowel_position_labels)

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(8, (3, 3), activation='relu', input_shape=(256, 256, 3)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(8, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])

In [ ]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(vowel_train, vowel_position_labels_train, epochs=5)

In [ ]:
test_loss, test_accuracy = model.evaluate(vowel_test, vowel_position_labels_test)
print ('Test loss: {}, Test accuracy: {}'.format(test_loss, test_accuracy*100))

In [ ]:
shuffled_vowels, shuffled_vowel_phoneme_labels = shuffle_data(vowel_images, vowel_phoneme_labels)

In [ ]:
vowel_train, vowel_test = split_data(shuffled_vowels)
vowel_phoneme_labels_train, vowel_phoneme_labels_test = split_data(shuffled_vowel_phoneme_labels)

In [ ]:
model2 = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(8, (3, 3), activation='relu', input_shape=(256, 256, 3)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(8, (3, 3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(13, activation='softmax')
])

In [ ]:
model2.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model2.fit(vowel_train, vowel_phoneme_labels_train, epochs=5)

In [ ]:
test_loss, test_accuracy = model2.evaluate(vowel_test, vowel_phoneme_labels_test)
print ('Test loss: {}, Test accuracy: {}'.format(test_loss, test_accuracy*100))

In [ ]:
out1 = model(vowel_train)

In [ ]:
print(out1)

In [ ]:
out2 = model2(vowel_train)

In [ ]:
print(out2)

In [ ]:
temp_out = []
for i in range(len(out1)):
    temp = np.concatenate((out1[i],out2[i]))
    temp_out.append(temp)
out3 = np.array(temp_out)

In [ ]:
print(out3[0])

In [ ]:
test_out1 = model(vowel_test)

In [ ]:
test_out2 = model2(vowel_test)

In [ ]:
temp_out = []
for i in range(len(test_out1)):
    temp = np.concatenate((test_out1[i],test_out2[i]))
    temp_out.append(temp)
test_out3 = np.array(temp_out)

In [ ]:
model3 = tf.keras.models.Sequential([
  tf.keras.layers.Dense(100, activation='sigmoid'),
  tf.keras.layers.Dense(13, activation='softmax')
])

In [ ]:
model3.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model3.fit(out3, vowel_phoneme_labels_train, epochs=25)

In [ ]:
test_loss, test_accuracy = model3.evaluate(test_out3, vowel_phoneme_labels_test)
print ('Test loss: {}, Test accuracy: {}'.format(test_loss, test_accuracy*100))

In [ ]:
def joint_output(input):
    out1 = model(input)
    out2 = model2(input)
    output = []
    
    for i in range(len(out1)):
        joint = np.concatenate((out1[i],out2[i]))
        output.append(joint)
    return np.array(output)

In [ ]:
out_test = joint_output(vowel_train)

In [ ]:
print(out_test[0])